### ISSUE TITLE
无限重启10.14.6

### ISSUE THREAD

**Issue by doudouaixiaoyu** [upupming/Lenovo-G50-80-Clover#1]
我也是联系g50-80，但是这个EFI在引导界面一直重启，请问怎么解决？

**Comment by upupming** [comment]
@doudouaixiaoyu 截一下图，看看报错信息。我这边没有遇到过。

**Comment by doudouaixiaoyu** [comment]
好，一个大神说可能是dvmt的问题，先不驱动显卡。我把截图发给你

截图可能不清楚，跑的太快了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yiming Li"<notifications@github.com&gt;; 
发送时间: 2019年10月17日(星期四) 上午9:35
收件人: "upupming/Lenovo-G50-80-Clover"<Lenovo-G50-80-Clover@noreply.github.com&gt;; 
抄送: "浩然"<1074045339@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [upupming/Lenovo-G50-80-Clover] 无限重启10.14.6 (#1)




@doudouaixiaoyu 截一下图，看看报错信息。我这边没有遇到过。

**Comment by doudouaixiaoyu** [comment]
说错了，是先不驱动显卡，但是他说你用的新的方式驱动显卡，不会出现dvmt问题啊

**Comment by doudouaixiaoyu** [comment]
![QQ图片20191017094827](https://user-images.githubusercontent.com/39321867/66971509-18181b00-f0c4-11e9-88f7-20e3f7abbf3b.jpg)

**Comment by upupming** [comment]
@doudouaixiaoyu 带 `FrameBuffer` 的大致上就是 DVMT 的问题，你可以先用不合法的ig-platform-id (0x12345678)来启动，系统装好之后再配置 WhateverGreen。

**Comment by doudouaixiaoyu** [comment]
这个，我这个系统是装好过了，我以前的笔记本装的黑苹果，我直接把固态拆下来放到联想g50-80上，把Clover换了，试试能不能启动，和这有关系吗？

**Comment by upupming** [comment]
@doudouaixiaoyu 理论上是没有关系的，但是黑苹果安装有很多需要注意的地方，不是随意复制一个 Clover 文件夹就可以完成的，推荐你按照自己机器的配置设置一下（你的配置可能和我的不一样），好好读一下本项目的 README，关于其中某个具体的地方有问题的话可以一起交流。

**Comment by doudouaixiaoyu** [comment]
好的，谢谢
