### ISSUE TITLE
纯UEFi启动花屏，自带键盘Alt和开始键反了

### ISSUE THREAD

**Issue by luckpi** [upupming/Lenovo-G50-80-Clover#3]
纯UEFI启动会花屏，必须睡眠在开才能解决

**Comment by upupming** [comment]
启动途中闪屏是正常现象（在tonymac上有相应参考，必须修改为 legacy first 模式，https://www.tonymacx86.com/threads/fix-resolve-boot-screen-garble.175799/ ），Alt就是cmd。
