### ISSUE TITLE
xcode无法下载

### ISSUE THREAD

**Issue by suwen00** [upupming/Lenovo-G50-80-Clover#5]
Xcode需要使用新版本的macos 但是无法更新,请问需要更改哪里以适应新版本的更新.

**Comment by upupming** [comment]
@suwen00 不好意思，已经换电脑了，现在没有继续更新的打算了，欢迎贡献 😅

**Comment by suwen00** [comment]
请问我需要怎么做可以更新到最新的版本呢  初接触黑苹果

**Comment by upupming** [comment]
直接系统设置更新就行，如果系统没有崩溃就OK，若是崩溃了，就想办法解决。

**Comment by suwen00** [comment]
没有崩溃但是更新后不能够更新  四叶草中有更新引导项目,不跑码.

**Comment by suwen00** [comment]
没有崩溃但是更新后不能够更新  四叶草中有更新引导项目,不跑码.

**Comment by upupming** [comment]
> 更新后不能够更新

不理解是啥意思。

> 四叶草中有更新引导项目

这个没用过，不清楚，我都是直接升级的

**Comment by suwen00** [comment]
稍等  我拍照您看看

**Comment by suwen00** [comment]
![WechatIMG1](https://user-images.githubusercontent.com/26670998/84345635-6c868280-abe0-11ea-93ca-d691ede9d90a.jpeg)
![WechatIMG2](https://user-images.githubusercontent.com/26670998/84345637-6e504600-abe0-11ea-8a06-82051589932d.jpeg)
更新后就是这样子

**Comment by upupming** [comment]
抱歉，这个我看不懂，没遇到过

**Comment by suwen00** [comment]
好的  我使用你这个看看能不能更新
